server:
  #服务配置
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: -1
spring:
  #数据库配置
  datasource:
    name: laundry
    url: jdbc:mysql://127.0.0.1:3306/laundry?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    #druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #前后缀
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    #HTTP 编码
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

    #配置rabbitmq的安装地址、端口以及账户信息
    #注意port 15672是管理端的端口
  application:
    name: name:spirng-boot-rabbitmq-sender
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ming
    password: 123456

  cache:
    type:
      redis
  redis:
    host: l27.0.0.1
    port: 6379
    # 密码,如果没有设置可以不填写，设置密码请看redis.conf的requirepass参数
    password: 123456
    # 如果使用的jedis 则将lettuce改成jedis即可
    jedis:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0


  #mybatis配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ming.ls.modules.sys.entity
  global-config:
    db-config:
      id-type: id_worker_str
      # 字段策略 0：“忽略判断”，1：“非NULL判断” 2：“非空判断”
      field-strategy: NOT_NULL
  #日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

